### ISSUE TITLE
3D STEP File missing

### ISSUE THREAD

**Issue by yashmulgaonkar** [sparkfun/SparkFun_RTK_Express_Plus#2]
Hello Sparkfun,
Can you please include a 3D step file for this?
We are truing to mount this in our rover and a 3D file would help a lot.
Thanks!

**Comment by nseidle** [comment]
Hi! We don't have the 3D file for the enclosure; we use an off the shelf Hammond Enclosure 1553BBK enclosure for these products. I suspect you can get the 3D file from Hammond.

**Comment by yashmulgaonkar** [comment]
Perfect! Thank you!
